env:
  - MONGO_URI=mongodb://localhost:27017/nodeschool-webinar

language: node_js

node_js:
  - 0.12.7

services:
  - mongodb

before_install:
 - npm install istanbul -g
 - npm install coveralls -g
 - npm install mocha -g

script:
  - npm test

after_success:
  - npm run coveralls